/* tslint:disable */
/* eslint-disable */
/**
 * Shared Types
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoItem
 */
export interface TodoItem {
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItem
     */
    isDone: boolean;
}

/**
 * Check if a given object implements the TodoItem interface.
 */
export function instanceOfTodoItem(value: object): value is TodoItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('isDone' in value) || value['isDone'] === undefined) return false;
    return true;
}

export function TodoItemFromJSON(json: any): TodoItem {
    return TodoItemFromJSONTyped(json, false);
}

export function TodoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'isDone': json['isDone'],
    };
}

export function TodoItemToJSON(value?: TodoItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'isDone': value['isDone'],
    };
}

