openapi: 3.0.3
info:
  title: Todo App API
  version: 1.0.0

paths:
  /todos:
    get:
      operationId: getTodos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'

components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        isDone:
          type: boolean
      required: [id, title, isDone]
